name: .NET CI/CD for Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-test:
    name: Build and Test .NET Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend # Set working directory for all run steps in this job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ConcordCloud.sln

    - name: Build solution
      run: dotnet build ConcordCloud.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ConcordCloud.sln --configuration Release --no-build --verbosity normal

    - name: Publish API project
      run: dotnet publish API/ConcordCloud.API.csproj --configuration Release --no-build -o ${{ github.workspace }}/app-publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-app
        path: ${{ github.workspace }}/app-publish 